import { Download, RefreshCw, UsersRound } from "lucide-react";
import { useCallback, useMemo } from "react";
import { useSearchParams } from "react-router-dom";
import { toast } from "sonner";

import { PaginationControls } from "../../../components/common/pagination-controls";
import { Alert } from "../../../components/ui/alert";
import { Button } from "../../../components/ui/button";
import { getApiErrorMessage } from "../../../services/api-client";
import { useScrapingJobs } from "../../scraping-jobs/hooks/use-scraping-jobs";
import type { ScrapingJobListFilters } from "../../scraping-jobs/types/scraping-job.types";
import { LeadEmptyState } from "../components/lead-empty-state";
import { LeadFilters } from "../components/lead-filters";
import { LeadTable } from "../components/lead-table";
import { LeadTableSkeleton } from "../components/lead-table-skeleton";
import { useExportLeads } from "../hooks/use-export-leads";
import { useLeads } from "../hooks/use-leads";
import type { LeadListFilters } from "../types/lead.types";
import {
  parseLeadFilters,
  serializeLeadFilters,
} from "../utils/lead-filter-params";

const jobOptionFilters: ScrapingJobListFilters = {
  page: 1,
  pageSize: 100,
  sortBy: "createdAt",
  sortOrder: "desc",
};

export function LeadExplorerPage() {
  const [searchParams, setSearchParams] = useSearchParams();
  const filters = useMemo(
    () => parseLeadFilters(searchParams),
    [searchParams],
  );
  const leadsQuery = useLeads(filters);
  const jobsQuery = useScrapingJobs(jobOptionFilters);
  const exportMutation = useExportLeads();

  const updateFilters = useCallback(
    (nextFilters: LeadListFilters) => {
      setSearchParams(serializeLeadFilters(nextFilters), { replace: true });
    },
    [setSearchParams],
  );

  const handleExport = async (): Promise<void> => {
    try {
      await exportMutation.mutateAsync(filters);
      toast.success("Filtered leads exported successfully.");
    } catch (error: unknown) {
      toast.error(getApiErrorMessage(error));
    }
  };

  const leads = leadsQuery.data?.leads ?? [];
  const hasFilters = searchParams.size > 0;
  const returnTo = `/dashboard/leads${
    searchParams.size > 0 ? `?${searchParams.toString()}` : ""
  }`;

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
        <div>
          <p className="text-sm font-semibold text-brand-700">Lead data</p>
          <h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-950">
            Lead explorer
          </h1>
          <p className="mt-2 max-w-2xl text-slate-600">
            Search, filter, and export only the business leads collected for
            your account.
          </p>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <Button
            aria-label="Refresh lead explorer"
            isLoading={leadsQuery.isFetching}
            loadingText="Refreshing"
            onClick={() => void leadsQuery.refetch()}
            variant="outline"
          >
            <RefreshCw aria-hidden="true" className="size-4" />
            Refresh
          </Button>
          <Button
            disabled={leadsQuery.isLoading}
            isLoading={exportMutation.isPending}
            loadingText="Exporting"
            onClick={() => void handleExport()}
          >
            <Download aria-hidden="true" className="size-4" />
            Export CSV
          </Button>
        </div>
      </div>

      <Alert title="Current filters are applied to exports" variant="info">
        CSV files are generated by the authenticated API and include only your
        matching leads. Large exports may require narrower filters.
      </Alert>

      <LeadFilters
        disabled={leadsQuery.isFetching}
        filters={filters}
        jobs={jobsQuery.data?.jobs ?? []}
        onChange={updateFilters}
      />

      {leadsQuery.isError ? (
        <Alert title="Could not load leads" variant="error">
          <p>{getApiErrorMessage(leadsQuery.error)}</p>
          <Button
            className="mt-3"
            onClick={() => void leadsQuery.refetch()}
            size="sm"
            variant="outline"
          >
            Try again
          </Button>
        </Alert>
      ) : null}

      {!leadsQuery.isError ? (
        <section
          aria-label="Business leads"
          className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"
        >
          <div className="flex items-center gap-3 border-b border-slate-200 px-4 py-4">
            <span className="flex size-9 items-center justify-center rounded-xl bg-brand-50 text-brand-700">
              <UsersRound aria-hidden="true" className="size-5" />
            </span>
            <div>
              <h2 className="text-sm font-semibold text-slate-900">
                Collected leads
              </h2>
              <p className="text-xs text-slate-500">
                {leadsQuery.data
                  ? `${leadsQuery.data.pagination.totalItems.toLocaleString()} matching records`
                  : "Loading records"}
              </p>
            </div>
          </div>
          {leadsQuery.isLoading ? <LeadTableSkeleton /> : null}
          {!leadsQuery.isLoading && leads.length === 0 ? (
            <div className="p-4">
              <LeadEmptyState filtered={hasFilters} />
            </div>
          ) : null}
          {!leadsQuery.isLoading && leads.length > 0 ? (
            <>
              <LeadTable leads={leads} returnTo={returnTo} />
              {leadsQuery.data ? (
                <PaginationControls
                  disabled={leadsQuery.isFetching}
                  onPageChange={(page) =>
                    updateFilters({ ...filters, page })
                  }
                  pagination={leadsQuery.data.pagination}
                />
              ) : null}
            </>
          ) : null}
        </section>
      ) : null}
    </div>
  );
}
